name: ldm
channels:
  - apple
  - conda-forge
  - pytorch-nightly
dependencies:
  - python=3.8.5
  - pytorch=1.13.0
  - torchvision=0.14.0
  - numpy>=1.19.5,<2.0a0
  - grpcio>=1.25.0
  - pip:
    - albumentations==0.4.3
    - opencv-python>=4.1
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers>=4.9
    - torchmetrics==0.6.0
    - kornia==0.6
    - tokenizers==0.11.6
    - .
